// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Institution struct {
	ID          uuid.UUID
	DisplayName string
	RorID       *string
	OpenalexID  *string
	CountryCode *string
	RawNames    []byte
	CreatedAt   pgtype.Timestamptz
}

type Paper struct {
	ID               uuid.UUID
	SourceType       string
	Status           string
	Title            *string
	Abstract         *string
	Doi              *string
	PublicationYear  *int32
	UploadedFilename string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	SourceID         *string
	PrimaryCategory  *string
}

type PaperAsset struct {
	ID            uuid.UUID
	PaperID       uuid.UUID
	AssetType     string
	StorageBucket string
	StorageKey    string
	ContentType   string
	SizeBytes     int64
	Checksum      *string
	CreatedAt     pgtype.Timestamptz
}

type PaperAuthor struct {
	ID               uuid.UUID
	PaperID          uuid.UUID
	AuthorOrder      int32
	DisplayName      string
	Orcid            *string
	OpenalexAuthorID *string
}

type PaperCard struct {
	ID            uuid.UUID
	PaperID       uuid.UUID
	SchemaVersion string
	Model         string
	ContentJson   []byte
	CreatedAt     pgtype.Timestamptz
}

type PaperEvidence struct {
	ID           uuid.UUID
	PaperID      uuid.UUID
	PaperCardID  pgtype.UUID
	ClaimKey     string
	EvidenceType string
	SectionID    pgtype.UUID
	AssetID      pgtype.UUID
	Page         *int32
	Locator      *string
	Snippet      *string
	Confidence   float64
	CreatedAt    pgtype.Timestamptz
}

type PaperFigure struct {
	ID           uuid.UUID
	PaperID      uuid.UUID
	Kind         string
	Label        string
	Caption      string
	FigureOrder  int32
	Page         *int32
	ImageAssetID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type PaperInstitution struct {
	ID             uuid.UUID
	PaperID        uuid.UUID
	InstitutionID  pgtype.UUID
	RawAffiliation string
	Role           string
	Source         string
	Confidence     float64
	CreatedAt      pgtype.Timestamptz
}

type PaperProcessingJob struct {
	ID           uuid.UUID
	PaperID      uuid.UUID
	Status       string
	TaskID       *string
	ErrorMessage *string
	AttemptCount int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

type PaperReference struct {
	ID             uuid.UUID
	PaperID        uuid.UUID
	ReferenceOrder int32
	Title          *string
	Authors        []byte
	Venue          *string
	Year           *int32
	Doi            *string
	RawText        *string
}

type PaperSection struct {
	ID            uuid.UUID
	PaperID       uuid.UUID
	SectionOrder  int32
	Heading       *string
	Text          string
	PageStart     *int32
	PageEnd       *int32
	GrobidPath    *string
	SectionNumber *string
}
