// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: papers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPaper = `-- name: CreatePaper :one
INSERT INTO papers (source_type, status, uploaded_filename)
VALUES ($1, $2, $3)
RETURNING id, source_type, status, title, abstract, doi, publication_year, uploaded_filename, created_at, updated_at
`

type CreatePaperParams struct {
	SourceType       string
	Status           string
	UploadedFilename string
}

func (q *Queries) CreatePaper(ctx context.Context, arg CreatePaperParams) (Paper, error) {
	row := q.db.QueryRow(ctx, createPaper, arg.SourceType, arg.Status, arg.UploadedFilename)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.Status,
		&i.Title,
		&i.Abstract,
		&i.Doi,
		&i.PublicationYear,
		&i.UploadedFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaperAsset = `-- name: CreatePaperAsset :one
INSERT INTO paper_assets (paper_id, asset_type, storage_bucket, storage_key, content_type, size_bytes, checksum)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, paper_id, asset_type, storage_bucket, storage_key, content_type, size_bytes, checksum, created_at
`

type CreatePaperAssetParams struct {
	PaperID       uuid.UUID
	AssetType     string
	StorageBucket string
	StorageKey    string
	ContentType   string
	SizeBytes     int64
	Checksum      *string
}

func (q *Queries) CreatePaperAsset(ctx context.Context, arg CreatePaperAssetParams) (PaperAsset, error) {
	row := q.db.QueryRow(ctx, createPaperAsset,
		arg.PaperID,
		arg.AssetType,
		arg.StorageBucket,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Checksum,
	)
	var i PaperAsset
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.AssetType,
		&i.StorageBucket,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const createProcessingJob = `-- name: CreateProcessingJob :one
INSERT INTO paper_processing_jobs (paper_id, status)
VALUES ($1, $2)
RETURNING id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at
`

type CreateProcessingJobParams struct {
	PaperID uuid.UUID
	Status  string
}

func (q *Queries) CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, createProcessingJob, arg.PaperID, arg.Status)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPaper = `-- name: GetPaper :one
SELECT id, source_type, status, title, abstract, doi, publication_year, uploaded_filename, created_at, updated_at FROM papers WHERE id = $1
`

func (q *Queries) GetPaper(ctx context.Context, id uuid.UUID) (Paper, error) {
	row := q.db.QueryRow(ctx, getPaper, id)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.Status,
		&i.Title,
		&i.Abstract,
		&i.Doi,
		&i.PublicationYear,
		&i.UploadedFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProcessingJob = `-- name: GetProcessingJob :one
SELECT id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at FROM paper_processing_jobs WHERE id = $1
`

func (q *Queries) GetProcessingJob(ctx context.Context, id uuid.UUID) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, getProcessingJob, id)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setProcessingJobTaskID = `-- name: SetProcessingJobTaskID :one
UPDATE paper_processing_jobs
SET task_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at
`

type SetProcessingJobTaskIDParams struct {
	ID     uuid.UUID
	TaskID *string
}

func (q *Queries) SetProcessingJobTaskID(ctx context.Context, arg SetProcessingJobTaskIDParams) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, setProcessingJobTaskID, arg.ID, arg.TaskID)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updatePaperMetadata = `-- name: UpdatePaperMetadata :one
UPDATE papers
SET title = $2,
    abstract = $3,
    doi = $4,
    publication_year = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, source_type, status, title, abstract, doi, publication_year, uploaded_filename, created_at, updated_at
`

type UpdatePaperMetadataParams struct {
	ID              uuid.UUID
	Title           *string
	Abstract        *string
	Doi             *string
	PublicationYear *int32
	Status          string
}

func (q *Queries) UpdatePaperMetadata(ctx context.Context, arg UpdatePaperMetadataParams) (Paper, error) {
	row := q.db.QueryRow(ctx, updatePaperMetadata,
		arg.ID,
		arg.Title,
		arg.Abstract,
		arg.Doi,
		arg.PublicationYear,
		arg.Status,
	)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.Status,
		&i.Title,
		&i.Abstract,
		&i.Doi,
		&i.PublicationYear,
		&i.UploadedFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProcessingJobStatus = `-- name: UpdateProcessingJobStatus :one
UPDATE paper_processing_jobs
SET status = $2,
    error_message = $3,
    attempt_count = attempt_count + $4,
    updated_at = now(),
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at
`

type UpdateProcessingJobStatusParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage *string
	AttemptCount int32
}

func (q *Queries) UpdateProcessingJobStatus(ctx context.Context, arg UpdateProcessingJobStatusParams) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, updateProcessingJobStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.AttemptCount,
	)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
