// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: papers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPaperSections = `-- name: CountPaperSections :one
SELECT count(*) FROM paper_sections WHERE paper_id = $1
`

func (q *Queries) CountPaperSections(ctx context.Context, paperID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPaperSections, paperID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaper = `-- name: CreatePaper :one
INSERT INTO papers (source_type, status, uploaded_filename)
VALUES ($1, $2, $3)
RETURNING id, source_type, status, title, abstract, doi, publication_year, uploaded_filename, created_at, updated_at
`

type CreatePaperParams struct {
	SourceType       string
	Status           string
	UploadedFilename string
}

func (q *Queries) CreatePaper(ctx context.Context, arg CreatePaperParams) (Paper, error) {
	row := q.db.QueryRow(ctx, createPaper, arg.SourceType, arg.Status, arg.UploadedFilename)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.Status,
		&i.Title,
		&i.Abstract,
		&i.Doi,
		&i.PublicationYear,
		&i.UploadedFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaperAsset = `-- name: CreatePaperAsset :one
INSERT INTO paper_assets (paper_id, asset_type, storage_bucket, storage_key, content_type, size_bytes, checksum)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, paper_id, asset_type, storage_bucket, storage_key, content_type, size_bytes, checksum, created_at
`

type CreatePaperAssetParams struct {
	PaperID       uuid.UUID
	AssetType     string
	StorageBucket string
	StorageKey    string
	ContentType   string
	SizeBytes     int64
	Checksum      *string
}

func (q *Queries) CreatePaperAsset(ctx context.Context, arg CreatePaperAssetParams) (PaperAsset, error) {
	row := q.db.QueryRow(ctx, createPaperAsset,
		arg.PaperID,
		arg.AssetType,
		arg.StorageBucket,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Checksum,
	)
	var i PaperAsset
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.AssetType,
		&i.StorageBucket,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const createPaperAuthor = `-- name: CreatePaperAuthor :one
INSERT INTO paper_authors (paper_id, author_order, display_name, orcid)
VALUES ($1, $2, $3, $4)
RETURNING id, paper_id, author_order, display_name, orcid, openalex_author_id
`

type CreatePaperAuthorParams struct {
	PaperID     uuid.UUID
	AuthorOrder int32
	DisplayName string
	Orcid       *string
}

func (q *Queries) CreatePaperAuthor(ctx context.Context, arg CreatePaperAuthorParams) (PaperAuthor, error) {
	row := q.db.QueryRow(ctx, createPaperAuthor,
		arg.PaperID,
		arg.AuthorOrder,
		arg.DisplayName,
		arg.Orcid,
	)
	var i PaperAuthor
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.AuthorOrder,
		&i.DisplayName,
		&i.Orcid,
		&i.OpenalexAuthorID,
	)
	return i, err
}

const createPaperCard = `-- name: CreatePaperCard :one
INSERT INTO paper_cards (paper_id, schema_version, model, content_json)
VALUES ($1, $2, $3, $4)
RETURNING id, paper_id, schema_version, model, content_json, created_at
`

type CreatePaperCardParams struct {
	PaperID       uuid.UUID
	SchemaVersion string
	Model         string
	ContentJson   []byte
}

func (q *Queries) CreatePaperCard(ctx context.Context, arg CreatePaperCardParams) (PaperCard, error) {
	row := q.db.QueryRow(ctx, createPaperCard,
		arg.PaperID,
		arg.SchemaVersion,
		arg.Model,
		arg.ContentJson,
	)
	var i PaperCard
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.SchemaVersion,
		&i.Model,
		&i.ContentJson,
		&i.CreatedAt,
	)
	return i, err
}

const createPaperEvidence = `-- name: CreatePaperEvidence :one
INSERT INTO paper_evidence (paper_id, paper_card_id, claim_key, evidence_type, section_id, asset_id, page, locator, snippet, confidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, paper_id, paper_card_id, claim_key, evidence_type, section_id, asset_id, page, locator, snippet, confidence, created_at
`

type CreatePaperEvidenceParams struct {
	PaperID      uuid.UUID
	PaperCardID  pgtype.UUID
	ClaimKey     string
	EvidenceType string
	SectionID    pgtype.UUID
	AssetID      pgtype.UUID
	Page         *int32
	Locator      *string
	Snippet      *string
	Confidence   float64
}

func (q *Queries) CreatePaperEvidence(ctx context.Context, arg CreatePaperEvidenceParams) (PaperEvidence, error) {
	row := q.db.QueryRow(ctx, createPaperEvidence,
		arg.PaperID,
		arg.PaperCardID,
		arg.ClaimKey,
		arg.EvidenceType,
		arg.SectionID,
		arg.AssetID,
		arg.Page,
		arg.Locator,
		arg.Snippet,
		arg.Confidence,
	)
	var i PaperEvidence
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.PaperCardID,
		&i.ClaimKey,
		&i.EvidenceType,
		&i.SectionID,
		&i.AssetID,
		&i.Page,
		&i.Locator,
		&i.Snippet,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const createPaperFigure = `-- name: CreatePaperFigure :one
INSERT INTO paper_figures (paper_id, kind, label, caption, figure_order, page, image_asset_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, paper_id, kind, label, caption, figure_order, page, image_asset_id, created_at
`

type CreatePaperFigureParams struct {
	PaperID      uuid.UUID
	Kind         string
	Label        string
	Caption      string
	FigureOrder  int32
	Page         *int32
	ImageAssetID pgtype.UUID
}

func (q *Queries) CreatePaperFigure(ctx context.Context, arg CreatePaperFigureParams) (PaperFigure, error) {
	row := q.db.QueryRow(ctx, createPaperFigure,
		arg.PaperID,
		arg.Kind,
		arg.Label,
		arg.Caption,
		arg.FigureOrder,
		arg.Page,
		arg.ImageAssetID,
	)
	var i PaperFigure
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Kind,
		&i.Label,
		&i.Caption,
		&i.FigureOrder,
		&i.Page,
		&i.ImageAssetID,
		&i.CreatedAt,
	)
	return i, err
}

const createPaperReference = `-- name: CreatePaperReference :one
INSERT INTO paper_references (paper_id, reference_order, title, authors, venue, year, doi, raw_text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, paper_id, reference_order, title, authors, venue, year, doi, raw_text
`

type CreatePaperReferenceParams struct {
	PaperID        uuid.UUID
	ReferenceOrder int32
	Title          *string
	Authors        []byte
	Venue          *string
	Year           *int32
	Doi            *string
	RawText        *string
}

func (q *Queries) CreatePaperReference(ctx context.Context, arg CreatePaperReferenceParams) (PaperReference, error) {
	row := q.db.QueryRow(ctx, createPaperReference,
		arg.PaperID,
		arg.ReferenceOrder,
		arg.Title,
		arg.Authors,
		arg.Venue,
		arg.Year,
		arg.Doi,
		arg.RawText,
	)
	var i PaperReference
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.ReferenceOrder,
		&i.Title,
		&i.Authors,
		&i.Venue,
		&i.Year,
		&i.Doi,
		&i.RawText,
	)
	return i, err
}

const createPaperSection = `-- name: CreatePaperSection :one
INSERT INTO paper_sections (paper_id, section_order, heading, text, page_start, page_end, grobid_path)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, paper_id, section_order, heading, text, page_start, page_end, grobid_path
`

type CreatePaperSectionParams struct {
	PaperID      uuid.UUID
	SectionOrder int32
	Heading      *string
	Text         string
	PageStart    *int32
	PageEnd      *int32
	GrobidPath   *string
}

func (q *Queries) CreatePaperSection(ctx context.Context, arg CreatePaperSectionParams) (PaperSection, error) {
	row := q.db.QueryRow(ctx, createPaperSection,
		arg.PaperID,
		arg.SectionOrder,
		arg.Heading,
		arg.Text,
		arg.PageStart,
		arg.PageEnd,
		arg.GrobidPath,
	)
	var i PaperSection
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.SectionOrder,
		&i.Heading,
		&i.Text,
		&i.PageStart,
		&i.PageEnd,
		&i.GrobidPath,
	)
	return i, err
}

const createProcessingJob = `-- name: CreateProcessingJob :one
INSERT INTO paper_processing_jobs (paper_id, status)
VALUES ($1, $2)
RETURNING id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at
`

type CreateProcessingJobParams struct {
	PaperID uuid.UUID
	Status  string
}

func (q *Queries) CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, createProcessingJob, arg.PaperID, arg.Status)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteFailedJobsOlderThan = `-- name: DeleteFailedJobsOlderThan :execrows
DELETE FROM paper_processing_jobs
WHERE status = 'failed' AND updated_at < $1
`

func (q *Queries) DeleteFailedJobsOlderThan(ctx context.Context, updatedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFailedJobsOlderThan, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePaperAuthors = `-- name: DeletePaperAuthors :exec
DELETE FROM paper_authors WHERE paper_id = $1
`

func (q *Queries) DeletePaperAuthors(ctx context.Context, paperID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaperAuthors, paperID)
	return err
}

const deletePaperCardsByPaper = `-- name: DeletePaperCardsByPaper :exec
DELETE FROM paper_cards WHERE paper_id = $1
`

func (q *Queries) DeletePaperCardsByPaper(ctx context.Context, paperID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaperCardsByPaper, paperID)
	return err
}

const deletePaperFiguresByPaper = `-- name: DeletePaperFiguresByPaper :exec
DELETE FROM paper_figures WHERE paper_id = $1
`

func (q *Queries) DeletePaperFiguresByPaper(ctx context.Context, paperID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaperFiguresByPaper, paperID)
	return err
}

const deletePaperReferences = `-- name: DeletePaperReferences :exec
DELETE FROM paper_references WHERE paper_id = $1
`

func (q *Queries) DeletePaperReferences(ctx context.Context, paperID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaperReferences, paperID)
	return err
}

const deletePaperSections = `-- name: DeletePaperSections :exec
DELETE FROM paper_sections WHERE paper_id = $1
`

func (q *Queries) DeletePaperSections(ctx context.Context, paperID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaperSections, paperID)
	return err
}

const getLatestPaperCard = `-- name: GetLatestPaperCard :one
SELECT id, paper_id, schema_version, model, content_json, created_at FROM paper_cards WHERE paper_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestPaperCard(ctx context.Context, paperID uuid.UUID) (PaperCard, error) {
	row := q.db.QueryRow(ctx, getLatestPaperCard, paperID)
	var i PaperCard
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.SchemaVersion,
		&i.Model,
		&i.ContentJson,
		&i.CreatedAt,
	)
	return i, err
}

const getPaper = `-- name: GetPaper :one
SELECT id, source_type, status, title, abstract, doi, publication_year, uploaded_filename, created_at, updated_at FROM papers WHERE id = $1
`

func (q *Queries) GetPaper(ctx context.Context, id uuid.UUID) (Paper, error) {
	row := q.db.QueryRow(ctx, getPaper, id)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.Status,
		&i.Title,
		&i.Abstract,
		&i.Doi,
		&i.PublicationYear,
		&i.UploadedFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaperAssetByType = `-- name: GetPaperAssetByType :one
SELECT id, paper_id, asset_type, storage_bucket, storage_key, content_type, size_bytes, checksum, created_at FROM paper_assets
WHERE paper_id = $1 AND asset_type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetPaperAssetByTypeParams struct {
	PaperID   uuid.UUID
	AssetType string
}

func (q *Queries) GetPaperAssetByType(ctx context.Context, arg GetPaperAssetByTypeParams) (PaperAsset, error) {
	row := q.db.QueryRow(ctx, getPaperAssetByType, arg.PaperID, arg.AssetType)
	var i PaperAsset
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.AssetType,
		&i.StorageBucket,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const getProcessingJob = `-- name: GetProcessingJob :one
SELECT id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at FROM paper_processing_jobs WHERE id = $1
`

func (q *Queries) GetProcessingJob(ctx context.Context, id uuid.UUID) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, getProcessingJob, id)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listPaperAuthors = `-- name: ListPaperAuthors :many
SELECT id, paper_id, author_order, display_name, orcid, openalex_author_id FROM paper_authors WHERE paper_id = $1 ORDER BY author_order
`

func (q *Queries) ListPaperAuthors(ctx context.Context, paperID uuid.UUID) ([]PaperAuthor, error) {
	rows, err := q.db.Query(ctx, listPaperAuthors, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperAuthor
	for rows.Next() {
		var i PaperAuthor
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.AuthorOrder,
			&i.DisplayName,
			&i.Orcid,
			&i.OpenalexAuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaperFigures = `-- name: ListPaperFigures :many
SELECT id, paper_id, kind, label, caption, figure_order, page, image_asset_id, created_at FROM paper_figures WHERE paper_id = $1 ORDER BY figure_order
`

func (q *Queries) ListPaperFigures(ctx context.Context, paperID uuid.UUID) ([]PaperFigure, error) {
	rows, err := q.db.Query(ctx, listPaperFigures, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperFigure
	for rows.Next() {
		var i PaperFigure
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.Kind,
			&i.Label,
			&i.Caption,
			&i.FigureOrder,
			&i.Page,
			&i.ImageAssetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaperReferences = `-- name: ListPaperReferences :many
SELECT id, paper_id, reference_order, title, authors, venue, year, doi, raw_text FROM paper_references WHERE paper_id = $1 ORDER BY reference_order
`

func (q *Queries) ListPaperReferences(ctx context.Context, paperID uuid.UUID) ([]PaperReference, error) {
	rows, err := q.db.Query(ctx, listPaperReferences, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperReference
	for rows.Next() {
		var i PaperReference
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.ReferenceOrder,
			&i.Title,
			&i.Authors,
			&i.Venue,
			&i.Year,
			&i.Doi,
			&i.RawText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaperSections = `-- name: ListPaperSections :many
SELECT id, paper_id, section_order, heading, text, page_start, page_end, grobid_path FROM paper_sections WHERE paper_id = $1 ORDER BY section_order
`

func (q *Queries) ListPaperSections(ctx context.Context, paperID uuid.UUID) ([]PaperSection, error) {
	rows, err := q.db.Query(ctx, listPaperSections, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaperSection
	for rows.Next() {
		var i PaperSection
		if err := rows.Scan(
			&i.ID,
			&i.PaperID,
			&i.SectionOrder,
			&i.Heading,
			&i.Text,
			&i.PageStart,
			&i.PageEnd,
			&i.GrobidPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPapers = `-- name: ListPapers :many
SELECT id, title, status, publication_year, uploaded_filename, created_at
FROM papers
ORDER BY created_at DESC
LIMIT 500
`

type ListPapersRow struct {
	ID               uuid.UUID
	Title            *string
	Status           string
	PublicationYear  *int32
	UploadedFilename string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListPapers(ctx context.Context) ([]ListPapersRow, error) {
	rows, err := q.db.Query(ctx, listPapers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPapersRow
	for rows.Next() {
		var i ListPapersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.PublicationYear,
			&i.UploadedFilename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFailedJob = `-- name: ResetFailedJob :execrows
UPDATE paper_processing_jobs
SET status = 'queued',
    attempt_count = 0,
    error_message = NULL,
    completed_at = NULL,
    updated_at = now()
WHERE id = $1 AND status = 'failed'
`

func (q *Queries) ResetFailedJob(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetFailedJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setJobStatusAndAttempt = `-- name: SetJobStatusAndAttempt :one
UPDATE paper_processing_jobs
SET status = $2,
    error_message = $3,
    attempt_count = $4,
    updated_at = now(),
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at
`

type SetJobStatusAndAttemptParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage *string
	AttemptCount int32
}

func (q *Queries) SetJobStatusAndAttempt(ctx context.Context, arg SetJobStatusAndAttemptParams) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, setJobStatusAndAttempt,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.AttemptCount,
	)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setPaperFigureImageAsset = `-- name: SetPaperFigureImageAsset :exec
UPDATE paper_figures
SET image_asset_id = $1
WHERE paper_id = $2 AND figure_order = $3
`

type SetPaperFigureImageAssetParams struct {
	ImageAssetID pgtype.UUID
	PaperID      uuid.UUID
	FigureOrder  int32
}

func (q *Queries) SetPaperFigureImageAsset(ctx context.Context, arg SetPaperFigureImageAssetParams) error {
	_, err := q.db.Exec(ctx, setPaperFigureImageAsset, arg.ImageAssetID, arg.PaperID, arg.FigureOrder)
	return err
}

const setProcessingJobTaskID = `-- name: SetProcessingJobTaskID :one
UPDATE paper_processing_jobs
SET task_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at
`

type SetProcessingJobTaskIDParams struct {
	ID     uuid.UUID
	TaskID *string
}

func (q *Queries) SetProcessingJobTaskID(ctx context.Context, arg SetProcessingJobTaskIDParams) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, setProcessingJobTaskID, arg.ID, arg.TaskID)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updatePaperMetadata = `-- name: UpdatePaperMetadata :one
UPDATE papers
SET title = $2,
    abstract = $3,
    doi = $4,
    publication_year = $5,
    status = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, source_type, status, title, abstract, doi, publication_year, uploaded_filename, created_at, updated_at
`

type UpdatePaperMetadataParams struct {
	ID              uuid.UUID
	Title           *string
	Abstract        *string
	Doi             *string
	PublicationYear *int32
	Status          string
}

func (q *Queries) UpdatePaperMetadata(ctx context.Context, arg UpdatePaperMetadataParams) (Paper, error) {
	row := q.db.QueryRow(ctx, updatePaperMetadata,
		arg.ID,
		arg.Title,
		arg.Abstract,
		arg.Doi,
		arg.PublicationYear,
		arg.Status,
	)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.Status,
		&i.Title,
		&i.Abstract,
		&i.Doi,
		&i.PublicationYear,
		&i.UploadedFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProcessingJobStatus = `-- name: UpdateProcessingJobStatus :one
UPDATE paper_processing_jobs
SET status = $2,
    error_message = $3,
    attempt_count = attempt_count + $4,
    updated_at = now(),
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, paper_id, status, task_id, error_message, attempt_count, created_at, updated_at, completed_at
`

type UpdateProcessingJobStatusParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage *string
	AttemptCount int32
}

func (q *Queries) UpdateProcessingJobStatus(ctx context.Context, arg UpdateProcessingJobStatusParams) (PaperProcessingJob, error) {
	row := q.db.QueryRow(ctx, updateProcessingJobStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.AttemptCount,
	)
	var i PaperProcessingJob
	err := row.Scan(
		&i.ID,
		&i.PaperID,
		&i.Status,
		&i.TaskID,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
