// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const deleteAppSetting = `-- name: DeleteAppSetting :exec
DELETE FROM app_settings WHERE key = $1
`

func (q *Queries) DeleteAppSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteAppSetting, key)
	return err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_at FROM app_settings
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.Query(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSetting
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertAppSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.Exec(ctx, upsertAppSetting, arg.Key, arg.Value)
	return err
}
